# Generated by Django 5.0.14 on 2026-06-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membershiplevel_customuser_total_deposited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jobs_completed_override',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='revenue_generated_override',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
