# Generated by Django 6.0.6 on 2026-06-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_jobs_completed_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='worker_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
