# Generated by Django 6.0.6 on 2026-06-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='additional_bookings', to='bookings.service'),
        ),
    ]
