# Generated by Django 6.0.6

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_additional_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='workers',
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={'role': 'worker'},
                related_name='worker_bookings_m2m',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
